### PR TITLE
Add QueryRepository for T-SQL View (Used DbQuery insteand DbSet)

### PR DESCRIPTION
**Pull request by MohMehrnia**
I Fixed Package for used By DbQuery and T-SQL View

### CODE REVIEW

**Comment by xyting** [comment]
Please directly use DbQuery insteand DbSet in `Repository` class

**Comment by MohMehrnia** [comment]
I dot not understand you instruction!, i create to repository on for dbset and one for dbquery

**Comment by xyting** [comment]
merge into one `Repository`

**Comment by kevingy** [comment]
@MohMehrnia It also looks like you need to resolve merge conflicts. The project structure has changed.

**Pull request closed without merging**
